name: Multi-Runner CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "Build on GitHub-hosted runner"

  test:
    runs-on: [self-hoste, de]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: echo "Tests on self-hosted Linux runner"

  deploy:
    runs-on: [self-hosted, amazonlinux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying from deploy runner"




# #github actions cicd pipeline 
# name: Terraform Deploy

# on:
#   push:
#     branches: [ main ]
#   #workflow_dispatch:   # ✅ Manual trigger only


# jobs:
#   terraform:
#     runs-on: self-hosted

#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: us-east-1 # change if needed

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Validate
#         run: terraform validate

#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       - name: Terraform Apply
#         run: terraform apply -auto-approve tfplan
